# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Toby Lightheart Research
email: toby.lightheart---at---gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Toby Lightheart's machine learning research website.
  Regular updates will be provided on the development of algorithms for changing the size of artificial neural networks.
  Blog posts will also include comments on related technology and social implications of artificial intelligence.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tobylightheart.github.io" # the base hostname & protocol for your site
twitter_username: tobylightheart
github_username:  tobylightheart

# Build settings
markdown: kramdown
